# Generated by Django 2.0.7 on 2018-07-26 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='units.Unit'),
        ),
    ]
