# Generated by Django 2.0.5 on 2018-05-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternatives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='answer',
        ),
    ]
