# Generated by Django 2.0.5 on 2018-05-25 00:11

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='document',
            name='uri',
            field=models.FileField(upload_to=documents.models.upload_to_dir),
        ),
    ]
