# Generated by Django 2.0.5 on 2018-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
    ]
