# Generated by Django 2.1 on 2018-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
