# Generated by Django 2.1 on 2018-08-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180816_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uri',
        ),
        migrations.AddField(
            model_name='video',
            name='embedded',
            field=models.TextField(blank=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/courses'),
        ),
    ]
