# Generated by Django 2.1 on 2018-08-17 13:56

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180816_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uri',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/courses', validators=[courses.validators.FileValidator(allowed_extensions=('.mp4', '.ogg', '.webm'), allowed_mimetypes=('media/mp4', 'media/ogg', 'media/webm'))]),
        ),
    ]
