# Generated by Django 2.1 on 2018-08-17 14:11

import courses.models
import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180817_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.upload_to_dir),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.upload_to_dir, validators=[courses.validators.FileValidator(allowed_extensions='pdf', allowed_mimetypes='application/pdf', max_size=104857600)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.upload_to_dir, validators=[courses.validators.FileValidator(allowed_extensions=('mp4', 'ogg', 'webm'), allowed_mimetypes=('media/mp4', 'media/ogg', 'media/webm'), max_size=104857600)]),
        ),
    ]
