# Generated by Django 2.1 on 2018-08-17 14:12

import courses.models
import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180817_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.upload_to_dir, validators=[courses.validators.FileValidator(allowed_extensions=('mp4', 'ogg', 'webm'), allowed_mimetypes=('video/mp4', 'video/ogg', 'video/webm'), max_size=104857600)]),
        ),
    ]
