# Generated by Django 2.1 on 2018-08-19 14:12

import courses.models
import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180817_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Não Iniciada'), (1, 'Em Andamento'), (2, 'Finalizada')], default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.upload_to_dir, validators=[courses.validators.FileValidator(allowed_extensions=('pdf',), allowed_mimetypes='application/pdf', max_size=104857600)]),
        ),
    ]
