# Generated by Django 2.1 on 2018-08-21 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20180821_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosed_alternative', models.CharField(max_length=10)),
                ('hit_the_answer', models.BooleanField(default=False)),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.Alternative')),
                ('exam_try', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.ExamTry')),
            ],
        ),
    ]
