# Generated by Django 2.1 on 2018-08-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choosed_alternative',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
