# Generated by Django 2.1 on 2018-08-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20180821_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Em andamento'), (1, 'Concluído')], default=0),
        ),
    ]
