# Generated by Django 2.1 on 2018-08-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_enrollment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name']},
        ),
    ]
