# Generated by Django 2.0.5 on 2018-05-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='contact',
            field=models.EmailField(max_length=100),
        ),
    ]
