# Generated by Django 2.0.5 on 2018-05-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(max_length=2000)),
                ('type', models.SmallIntegerField(choices=[(1, 'Video'), (2, 'Document')])),
                ('activity', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='activities.Activity')),
            ],
        ),
    ]
