# Generated by Django 2.0.5 on 2018-05-18 00:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('courses', '0003_auto_20180517_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='keywords',
        ),
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
