# Generated by Django 2.0.5 on 2018-05-18 01:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180518_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='keywords'),
        ),
    ]
