# Generated by Django 2.0.4 on 2018-04-10 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.IntegerField(choices=[(0, 'Vídeo'), (1, 'Material Complementar'), (2, 'Avaliação')], default=0)),
            ],
            options={
                'db_table': 'atividade',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('criado_em', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('palavras_chave', models.CharField(max_length=100, null=True, verbose_name='Palavras-Chave')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.Categoria')),
            ],
            options={
                'db_table': 'curso',
                'ordering': ('criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('resumo', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'instrutor',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='cursos.Curso')),
            ],
            options={
                'db_table': 'unidade',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('atitivade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cursos.Atividade')),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
        migrations.CreateModel(
            name='MaterialComplementar',
            fields=[
                ('uri', models.URLField()),
                ('atitivade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cursos.Atividade')),
            ],
            options={
                'db_table': 'material_compl',
            },
        ),
        migrations.CreateModel(
            name='VideoAula',
            fields=[
                ('uri', models.URLField()),
                ('atitivade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cursos.Atividade')),
            ],
            options={
                'db_table': 'video_aula',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instrutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.Instrutor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='cursos.Unidade'),
        ),
    ]
