# Generated by Django 2.0.4 on 2018-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='palavras_chave',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
