# Generated by Django 2.0.4 on 2018-04-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='atitivade',
            new_name='atividade',
        ),
        migrations.RenameField(
            model_name='materialcomplementar',
            old_name='atitivade',
            new_name='atividade',
        ),
        migrations.RenameField(
            model_name='videoaula',
            old_name='atitivade',
            new_name='atividade',
        ),
    ]
