# Generated by Django 2.0.4 on 2018-04-10 00:45

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_atividade_materialcomplementar_videoaula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialcomplementar',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='videoaula',
            name='atividade',
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cursos.atividade',),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Vídeo'), (1, 'Material Complementar'), (2, 'Avaliação')], default=0),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='criado_em',
            field=models.DateField(auto_now=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='palavras_chave',
            field=models.CharField(max_length=100, null=True, verbose_name='Palavras-Chave'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.DeleteModel(
            name='MaterialComplementar',
        ),
        migrations.DeleteModel(
            name='VideoAula',
        ),
        migrations.CreateModel(
            name='MaterialComplementar',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cursos.atividade', cursos.models.Recurso),
        ),
        migrations.CreateModel(
            name='VideoAula',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('cursos.atividade', cursos.models.Recurso),
        ),
    ]
