# Generated by Django 2.0.4 on 2018-04-12 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=500)),
                ('justificativa', models.TextField(max_length=500)),
                ('correta', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'alternativa',
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(max_length=2000)),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Vídeo'), (2, 'Material')])),
            ],
            options={
                'db_table': 'video_aula',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
            ],
            options={
                'db_table': 'atividade',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('criado_em', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('palavras_chave', models.CharField(max_length=100, null=True, verbose_name='Palavras-Chave')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='api.Categoria')),
            ],
            options={
                'db_table': 'curso',
                'ordering': ('criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('resumo', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'instrutor',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(max_length=500)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api.Avaliacao')),
            ],
            options={
                'db_table': 'questao',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='api.Curso')),
            ],
            options={
                'db_table': 'unidade',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instrutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='api.Instrutor'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api.Unidade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='api.Unidade'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='atividade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo', to='api.Atividade'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='questao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alternativa', to='api.Questao'),
        ),
    ]
