# Generated by Django 2.0.4 on 2018-04-14 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='questao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternativa', to='api.Questao'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='atividade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivo', to='api.Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='api.Unidade'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='api.Unidade'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api', to='api.Categoria'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='instrutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api', to='api.Instrutor'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='avaliacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='api.Avaliacao'),
        ),
    ]
