# Generated by Django 2.0.4 on 2018-04-15 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='atividade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivo', to='api.Atividade'),
        ),
    ]
