# Generated by Django 2.0.4 on 2018-04-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_avaliacao_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='api.Questao'),
        ),
    ]
